package net.shagie.studentnotify.rules

import net.shagie.studentnotify.data.Student
import net.shagie.studentnotify.data.Notification
import net.shagie.studentnotify.data.NotifyIds

global java.util.List notifications;

dialect "mvel"

/* If there is no previous enrolment notifcation,
 * add that notification.
 */

rule "enrolled Null"
    when
        $s : Student( notifications == null || notifications.isEmpty() )
    then
        notifications.add(new Notification(NotifyIds.ENROLL,
            ($s.getGrades() == null || $s.getGrades().isEmpty()) ? 0 : $s.getGrades().size(),
            "enrolled " + $s.getName()));
end

rule "enrolled NoPrevious"
    when
        $s : Student( notifications != null, !notifications.isEmpty(), $n : notifications )
        not Notification(id == NotifyIds.ENROLL) from $n
    then
        notifications.add(new Notification(NotifyIds.ENROLL,
            ($s.getGrades() == null || $s.getGrades().isEmpty()) ? 0 : $s.getGrades().size(),
            "enrolled " + $s.getName()));
end
