package net.shagie.studentnotify.rules

import net.shagie.studentnotify.data.Student
import net.shagie.studentnotify.data.Notification
import net.shagie.studentnotify.data.NotifyIds

global java.util.List newEvents;

dialect "mvel"

/* If there is no previous enrolment notifcation,
 * add that notification.
 */

rule "enrolled"
    when
        $s : Student( $studentId : studentId)
        not Notification( student == $studentId, notificationType == NotifyIds.ENROLL )
    then
        newEvents.add(new Notification(NotifyIds.ENROLL,
            $s.getStudentId(),
            ($s.getGrades() == null || $s.getGrades().isEmpty()) ? 0 : $s.getGrades().size(),
            "enrolled " + $s.getName()));
end