package net.shagie.studentnotify.rules

import net.shagie.studentnotify.data.Student
import net.shagie.studentnotify.data.Semester
import net.shagie.studentnotify.data.Notification
import java.util.*

global java.util.List notifications;

dialect "mvel"

/* Triggers every semester as long as the student maintains all As */

rule "straight As"
    when
        $s : Student(
            grades != null,
            $g : grades,
            $n : notifications
        )
        not Semester(reading != "A" || writing != "A" || math != "A") from $g
        not Notification(id == 2, semester == $g.size()) from $n
    then
        notifications.add(new Notification(2,
            ($s.getGrades() == null || $s.getGrades().isEmpty()) ? 0 : $s.getGrades().size(),
            "allAs " + $s.getName()));
end
