package net.shagie.studentnotify.rules

import net.shagie.studentnotify.data.Student
import net.shagie.studentnotify.data.Semester
import java.util.ArrayList

global java.util.List notifications;

////////////

rule "straight As"
    when
        $s : Student(grades != null, !grades.empty, $g : grades)
        $a : ArrayList() from collect
            ( Semester( reading == "A" ) from $g )
    then
        System.out.println($s.getId() + ": semesters: " + $g.size());
        System.out.println($s.getId() + " : " + $g);
        System.out.println($s.getId() + ": not As: " + $a.size());
        notifications.add("allAs");
end

////////////

rule "enrolled"
    when
        $s : Student()
    then
        notifications.add("enrolled " + $s.getName());
end

////////////

rule "last semester"
    when
        $s : Student(getGrades() != null)
    then
        notifications.add("there: " + $s.getGrades().get($s.getGrades().size() - 1));
end