package net.shagie.studentnotify.rules

import net.shagie.studentnotify.data.Student
import net.shagie.studentnotify.data.Semester
import java.util.*

global java.util.List notifications;

dialect "mvel"

////////////

rule "straight As"
    when
        $s : Student(
            grades != null,
            $g : grades
        )
        not Semester(reading != "A" || writing != "A" || math != "A") from $g
    then
        notifications.add("allAs");
end

////////////

rule "enrolled"
    when
        $s : Student()
    then
        notifications.add("enrolled " + $s.getName());
end

////////////

rule "last semester"
    when
        $s : Student(
            grades != null,
            $g : grades,
            $l : grades.get(grades.size() - 1)
        )
    then
        notifications.add("last semester: " + $l);
end